server_url: headscale-production.up.railway.app
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090

noise:
  private_key_path: /var/lib/headscale/noise_private.key

db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite

ephemeral_node_inactivity_timeout: 30m

derp:
  auto_update_enabled: true

log:
  format: text
  level: info
