server_url: headscale-production.up.railway.app
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
allocation: sequential

derp:
  auto_update_enabled: true

db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite
