# Headscale configuration
server_url: http://localhost:8081
listen_addr: 0.0.0.0:8080

# gRPC configuration
grpc_listen_addr: 0.0.0.0:50443
grpc_allow_insecure: false

# Noise private key (required for Tailscale v2)
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# Database
database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/db.sqlite

# IP prefixes
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

# DERP configuration
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default

# DNS configuration (updated syntax)
dns:
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8
  search_domains: []
  magic_dns: true
  base_domain: example.com

# Logging
log:
  level: info